name = "JLCL"
uuid = "cc15090e-1e6b-4c7b-9eb6-d2b5646cebf8"
authors = ["Marco Antoniotti"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
